### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HenriBeck** [TF2PickupNET/maps#1]
- [ ] Move data and images from main repo
- [ ] Add circleci integration
- [ ] Add a test script
  - [ ] Validate the data of the maps (all properties etc.)
  - [ ] Validate that each map has an image associated
